// TODO Basically a compute shader variant of the meshshader for UI
// generate meshes based on simple parameters in abstract structures like UIElements
// could be simple lines, radius, curve etc. can be very similar to the UI meshshader but saves
// to vram this shader could also do 3D (dont know if the ui shader should do that), thing this
// shader could do could also be generate geometry based on parameters and math, use predefined
// functions like sin cos, circle, exp etc. UBERSHADER
